#include <iostream>
#include <string>
using namespace std;

/* This class is used to provide HTML header, footer and style to the output files. */ 

class provide_htmlcss {

	public:	
		std::string allstyle; /* used for storing all the css */

		provide_htmlcss() {
			allstyle="";
		}

		std::string header(std::string title) {
		std::string head="<!DOCTYPE html>\n<html lang=\"en\">\n<head>\n<meta charset=\"utf-8\">\n<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\n<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n<title>"+title+"</title>\n<!-- Bootstrap -->\n<link href=\"css/bootstrap.css\" rel=\"stylesheet\">\n<link href=\"css/style.css\" rel=\"stylesheet\">\n<script src=\"js/jquery-1.11.2.js\"></script>\n<script src=\"js/bootstrap.js\"></script>\n<!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->\n<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->\n<!--[if lt IE 9]>\n<script src=\"js/html5shiv.js\"></script>\n<script src=\"js/respond.js\"></script>\n<![endif]-->\n</head>\n<body>\n";
  		return head;
	}

			std::string footer() {
				std::string footer = "</body>\n<credits> This webpage is generated by the ALANG Markdown to HTML converter. Not for commerical use.</credits>";
				return footer;
			}

		void addstyle(std::string newstyle) {
			allstyle=allstyle+"\n";
		}	

		~provide_htmlcss() { /* Destructor */
			/* Modify this */
			cout<<"#####\nObject deleted"<<endl;
			//Aditya.addcss(allstyle);
		}

};

int main() {
	provide_htmlcss a;
	cout<<a.header("#########")<<a.footer();
}